/*
	Перевірити роботу описаної установки SET QUOTED_INDENTIFIRER.
*/

USE DB_Books

SET QUOTED_IDENTIFIER ON
CREATE TABLE [TABLE] ([identity] INT IDENTITY , "NAME" NCHAR(20));
INSERT INTO "TABLE" ("NAME")
VALUES ('MAKSYM'),('ALEKEY')

--ERROR 
INSERT INTO "TABLE" ("NAME")
VALUES ("IHOR")
--ERROR

DROP TABLE [TABLE]

SET QUOTED_IDENTIFIER OFF
CREATE TABLE [TABLE] ([identity] INT IDENTITY , [NAME] NCHAR(20));
INSERT INTO [TABLE] ([NAME])
VALUES ("MAKSYM"),('ALEKEY')

--ERROR 
INSERT INTO "TABLE" ("NAME")
VALUES ('IHOR')
--ERROR

DROP TABLE [TABLE]

SET QUOTED_IDENTIFIER ON